# Generated by Django 4.2.14 on 2026-04-01 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('video', 'Video'), ('music', 'Music'), ('podcast', 'Podcast'), ('movie', 'Movie'), ('news', 'News')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=150)),
                ('source', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
                ('moods', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('duration_label', models.CharField(blank=True, max_length=40)),
                ('release_year', models.PositiveIntegerField(default=2024)),
                ('published_at', models.DateField()),
                ('popularity_score', models.FloatField(default=50)),
                ('quality_score', models.FloatField(default=50)),
                ('cross_domain_tags', models.CharField(blank=True, max_length=250)),
                ('card_theme', models.CharField(default='sunrise', max_length=80)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-popularity_score', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Guest', max_length=120)),
                ('favorite_domains', models.CharField(blank=True, max_length=200)),
                ('favorite_genres', models.CharField(blank=True, max_length=300)),
                ('current_mood', models.CharField(blank=True, max_length=80)),
                ('time_budget', models.CharField(choices=[('quick', 'Quick break'), ('focused', 'Focused session'), ('deep', 'Deep dive')], default='focused', max_length=20)),
                ('discovery_mode', models.CharField(choices=[('balanced', 'Balanced'), ('comfort', 'Comfort picks'), ('explorer', 'Explorer mode')], default='balanced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('liked', 'Liked'), ('saved', 'Saved'), ('disliked', 'Disliked')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommender.contentitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommender.userprofile')),
            ],
            options={
                'unique_together': {('profile', 'content', 'action')},
            },
        ),
    ]
