# Generated by Django 4.2.14 on 2026-04-01 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['domain', 'provider_rank', '-recommendation_score', '-published_at']},
        ),
        migrations.AddField(
            model_name='contentitem',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='keyword_blob',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='provider',
            field=models.CharField(default='internal', max_length=40),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='provider_content_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='provider_like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='provider_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='provider_save_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='provider_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='recommendation_score',
            field=models.FloatField(default=0),
        ),
    ]
