# Generated by Django 4.2.14 on 2026-04-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_syncstate_alter_contentitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='ai_mood',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='ai_recommendation_note',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='ai_topics',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
