from datetime import date

from django.core.management.base import BaseCommand

from recommender.models import ContentItem


CONTENT_SEED = [
    {"domain": "video", "title": "AI Builders Weekly", "creator": "Makers Orbit", "source": "StreamSphere", "genre": "technology", "moods": "curious,inspired", "description": "A sharp weekly breakdown of product launches, startup bets, and practical AI workflows.", "duration_label": "12 min", "release_year": 2026, "published_at": date(2026, 3, 30), "popularity_score": 82, "quality_score": 87, "cross_domain_tags": "ai,startups,product", "card_theme": "aurora", "is_featured": True},
    {"domain": "video", "title": "Designing Calm Interfaces", "creator": "Pixel Study", "source": "VisionPlay", "genre": "culture", "moods": "relaxed,focused", "description": "A visual essay on interface minimalism, human attention, and more grounded digital products.", "duration_label": "18 min", "release_year": 2025, "published_at": date(2026, 3, 25), "popularity_score": 74, "quality_score": 85, "cross_domain_tags": "design,ux,productivity", "card_theme": "sand"},
    {"domain": "video", "title": "Future of Urban Mobility", "creator": "NextCity Lab", "source": "Documenta", "genre": "documentary", "moods": "curious,focused", "description": "Compact documentary reporting on EV infrastructure, walkable cities, and last-mile innovation.", "duration_label": "26 min", "release_year": 2026, "published_at": date(2026, 3, 20), "popularity_score": 78, "quality_score": 81, "cross_domain_tags": "cities,sustainability,transport", "card_theme": "forest"},
    {"domain": "music", "title": "Quiet Momentum", "creator": "North Harbor", "source": "PulseAudio", "genre": "productivity", "moods": "focused,relaxed", "description": "Instrumental electronic textures built for deep work without becoming background wallpaper.", "duration_label": "42 min", "release_year": 2025, "published_at": date(2026, 2, 14), "popularity_score": 88, "quality_score": 84, "cross_domain_tags": "focus,deep-work", "card_theme": "midnight", "is_featured": True},
    {"domain": "music", "title": "Sunlit Commute", "creator": "Blue Terrace", "source": "PulseAudio", "genre": "indie", "moods": "upbeat,inspired", "description": "Warm indie pop for commuting, sketching, and shaking off a slow afternoon.", "duration_label": "36 min", "release_year": 2026, "published_at": date(2026, 3, 10), "popularity_score": 79, "quality_score": 80, "cross_domain_tags": "indie,energy,commute", "card_theme": "sunrise"},
    {"domain": "music", "title": "Signal in the Rain", "creator": "Echo District", "source": "TuneFlow", "genre": "science", "moods": "curious,relaxed", "description": "Ambient concept album inspired by astronomy, late-night coding, and city weather.", "duration_label": "48 min", "release_year": 2024, "published_at": date(2026, 1, 28), "popularity_score": 71, "quality_score": 83, "cross_domain_tags": "space,ambient,coding", "card_theme": "violet"},
    {"domain": "podcast", "title": "Product Sense", "creator": "Aisha Raman", "source": "PodNest", "genre": "business", "moods": "focused,inspired", "description": "Founders and product leaders unpack why certain digital experiences keep winning attention and trust.", "duration_label": "45 min", "release_year": 2026, "published_at": date(2026, 3, 29), "popularity_score": 85, "quality_score": 88, "cross_domain_tags": "startup,product,leadership", "card_theme": "copper", "is_featured": True},
    {"domain": "podcast", "title": "The Science Briefing", "creator": "Dr. Lina Torres", "source": "PodNest", "genre": "science", "moods": "curious,focused", "description": "Reliable science communication covering climate, biotech, and the research signals that matter.", "duration_label": "28 min", "release_year": 2026, "published_at": date(2026, 3, 27), "popularity_score": 77, "quality_score": 90, "cross_domain_tags": "research,climate,biotech", "card_theme": "ice"},
    {"domain": "podcast", "title": "Slow Growth Club", "creator": "Milan & Rae", "source": "VoiceDock", "genre": "wellness", "moods": "relaxed,inspired", "description": "Gentle conversations on sustainable ambition, rest, and designing a more resilient routine.", "duration_label": "34 min", "release_year": 2025, "published_at": date(2026, 3, 1), "popularity_score": 73, "quality_score": 86, "cross_domain_tags": "wellbeing,career,balance", "card_theme": "sage"},
    {"domain": "movie", "title": "Static Horizon", "creator": "Nadia Sol", "source": "CineVerse", "genre": "thriller", "moods": "focused,inspired", "description": "A tense newsroom thriller about misinformation, satellite failures, and a city on edge.", "duration_label": "118 min", "release_year": 2025, "published_at": date(2026, 2, 2), "popularity_score": 84, "quality_score": 89, "cross_domain_tags": "journalism,investigation,technology", "card_theme": "ember", "is_featured": True},
    {"domain": "movie", "title": "Field Notes for Tomorrow", "creator": "Kenji Murata", "source": "CineVerse", "genre": "documentary", "moods": "curious,inspired", "description": "A hopeful documentary following community labs, climate inventors, and everyday systems change.", "duration_label": "96 min", "release_year": 2026, "published_at": date(2026, 3, 8), "popularity_score": 76, "quality_score": 91, "cross_domain_tags": "climate,innovation,communities", "card_theme": "meadow"},
    {"domain": "movie", "title": "Soft Orbit", "creator": "Eva Porter", "source": "MotionDeck", "genre": "indie", "moods": "relaxed,upbeat", "description": "A gentle indie drama about friendship, migration, and building a life in a new city.", "duration_label": "102 min", "release_year": 2024, "published_at": date(2026, 1, 12), "popularity_score": 69, "quality_score": 84, "cross_domain_tags": "human stories,city life", "card_theme": "peach"},
    {"domain": "news", "title": "Markets Shift Toward Local Manufacturing", "creator": "Riya Sen", "source": "Daily Ledger", "genre": "business", "moods": "curious,focused", "description": "An analysis of supply chain resets, industrial policy, and new investment corridors.", "duration_label": "6 min read", "release_year": 2026, "published_at": date(2026, 3, 31), "popularity_score": 81, "quality_score": 83, "cross_domain_tags": "economy,industry,policy", "card_theme": "steel", "is_featured": True},
    {"domain": "news", "title": "What the New AI Safety Rules Mean for Startups", "creator": "Noah Price", "source": "Signal Daily", "genre": "technology", "moods": "focused,curious", "description": "A practical breakdown of emerging compliance expectations for smaller product teams.", "duration_label": "8 min read", "release_year": 2026, "published_at": date(2026, 3, 30), "popularity_score": 90, "quality_score": 85, "cross_domain_tags": "ai,policy,startups", "card_theme": "neon"},
    {"domain": "news", "title": "Community Clinics Test Low-Cost Diagnostics", "creator": "Tara Joel", "source": "Public Wire", "genre": "science", "moods": "curious,inspired", "description": "Field reporting on affordable diagnostics and the partnerships helping rural health systems scale.", "duration_label": "7 min read", "release_year": 2026, "published_at": date(2026, 3, 28), "popularity_score": 72, "quality_score": 88, "cross_domain_tags": "health,biotech,impact", "card_theme": "mint"},
    {"domain": "podcast", "title": "Media Mix", "creator": "Sam & Priya", "source": "VoiceDock", "genre": "culture", "moods": "upbeat,curious", "description": "One episode connects the week across internet culture, films, albums, and platform behavior.", "duration_label": "52 min", "release_year": 2026, "published_at": date(2026, 3, 26), "popularity_score": 80, "quality_score": 82, "cross_domain_tags": "culture,media,recommendations", "card_theme": "berry"},
    {"domain": "video", "title": "Five Tools for Better Learning Loops", "creator": "Sprint Scholar", "source": "StreamSphere", "genre": "learning", "moods": "focused,inspired", "description": "Actionable habits and tools to retain more from books, lectures, and online courses.", "duration_label": "9 min", "release_year": 2026, "published_at": date(2026, 3, 24), "popularity_score": 86, "quality_score": 84, "cross_domain_tags": "study,productivity,learning", "card_theme": "lemon"},
    {"domain": "music", "title": "Afterglow Office Hours", "creator": "Circuit Bloom", "source": "TuneFlow", "genre": "technology", "moods": "focused,upbeat", "description": "Synthwave with enough movement to energize shipping day without becoming chaotic.", "duration_label": "31 min", "release_year": 2026, "published_at": date(2026, 3, 15), "popularity_score": 75, "quality_score": 79, "cross_domain_tags": "coding,energy,ship-it", "card_theme": "electric"},
    {"domain": "movie", "title": "Last Broadcast at Dawn", "creator": "Iris Kent", "source": "MotionDeck", "genre": "business", "moods": "focused,curious", "description": "A newsroom drama exploring media consolidation, ethics, and the economics of attention.", "duration_label": "110 min", "release_year": 2025, "published_at": date(2026, 2, 20), "popularity_score": 72, "quality_score": 87, "cross_domain_tags": "media,business,ethics", "card_theme": "charcoal"},
    {"domain": "news", "title": "Universities Rethink Skills-First Degrees", "creator": "Daniel Hart", "source": "Morning Index", "genre": "learning", "moods": "curious,inspired", "description": "How institutions are redesigning programs around applied capability rather than course accumulation.", "duration_label": "5 min read", "release_year": 2026, "published_at": date(2026, 3, 29), "popularity_score": 68, "quality_score": 81, "cross_domain_tags": "education,skills,future-of-work", "card_theme": "sky"},
    {"domain": "podcast", "title": "Inside the Edit", "creator": "Kara Bloom", "source": "PodNest", "genre": "learning", "moods": "focused,curious", "description": "Editors explain how they shape stories, films, and interviews into something memorable.", "duration_label": "39 min", "release_year": 2025, "published_at": date(2026, 3, 18), "popularity_score": 71, "quality_score": 84, "cross_domain_tags": "storytelling,craft,media", "card_theme": "plum"},
]


class Command(BaseCommand):
    help = "Seed the database with cross-domain recommendation content."

    def handle(self, *args, **options):
        created = 0
        for entry in CONTENT_SEED:
            _, was_created = ContentItem.objects.update_or_create(
                title=entry["title"],
                domain=entry["domain"],
                defaults=entry,
            )
            if was_created:
                created += 1
        self.stdout.write(self.style.SUCCESS(f"Seed complete. {created} new items added, {len(CONTENT_SEED)} total synced."))
